# Generated by Django 3.1.4 on 2020-12-29 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20201229_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='emails', to='contact.email')),
                ('name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='user_name', to='contact.contact_data')),
                ('phones', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='phones', to='contact.phone')),
            ],
        ),
    ]
