# Generated by Django 3.1.4 on 2020-12-29 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='user_name',
        ),
    ]
