# Generated by Django 3.1.4 on 2020-12-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20201229_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='phone',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
