# Generated by Django 3.1.4 on 2020-12-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20201229_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
