# Generated by Django 3.1.4 on 2020-12-29 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_auto_20201229_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='phone',
        ),
    ]
